### ISSUE TITLE
Keeps buffing same target over and over

### ISSUE THREAD

**Issue by ZehelFenris** [phoosa/elvui_easybuff#10]
I have run into a problem when im in party it keeps on buffing the same player over and over instead of going to the next party member or myself.
It happens on my mage and paladin dont know about others as i havent played other classes with buffs  and its on my low level chars so just the regular arcane intellect and blessings

**Comment by Kabulla** [comment]
> I have run into a problem when im in party it keeps on buffing the same player over and over instead of going to the next party member or myself.
> It happens on my mage and paladin dont know about others as i havent played other classes with buffs and its on my low level chars so just the regular arcane intellect and blessings

I would like to second that...

**Comment by phoosa** [comment]
Fixed in version 1.5.1
