### ISSUE TITLE
Casting Mark of the Wild twice

### ISSUE THREAD

**Issue by Cryopier** [phoosa/elvui_easybuff#16]
When I use it as a Druid, it is casting Mark of the Wild on me twice, wasting mana.

**Comment by Cryopier** [comment]
Now, today when I login, it just casts Thorns over and over.  It won't even cast Mark of the Wild.

**Comment by phoosa** [comment]
Finally found some time to work on this thing again, I've completely rewritten it from scratch to both add new features and to resolve issues created by WOW API changes and my inability to maintain this code for months.
