### ISSUE TITLE
EasyBuff not working 

### ISSUE THREAD

**Issue by Binni0911** [phoosa/elvui_easybuff#17]
I downloaded easy buff just before the last update of wotlk and it was working fine but after the update, it has not worked at all for me I have deleted it and reinstalled it. Changed key binds and it just does not work at all for me. I'm all out of ideas on how to get it working again. Hopefully, there is a simple solution to this

**Comment by phoosa** [comment]
Finally found some time to work on this thing again, I've completely rewritten it from scratch to both add new features and to resolve issues created by WOW API changes and my inability to maintain this code for months.
