### ISSUE TITLE
cant open elvui config while easybuff is enabled

### ISSUE THREAD

**Issue by Shenanigan83** [phoosa/elvui_easybuff#18]
On my warrior, I cant open elvui config if easybuff is enabled. I dont have this problem on my mage.  I used buggrabber addon and here are the errors it shows 

4x ...nfig-3.0/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua:1969: AceConfigRegistry-3.0-21-ElvUI:ValidateOptionsTable(): ElvUI.args.EasyBuff.args.wanted.args.party.args.roleBuffs.args.partyRoleBuffs.args.Tanks.args: expected a table, got 'nil'
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:50: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:45>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:229: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:224>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:266: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:273: in function <...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:238>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:301: in function `ValidateOptionsTable'
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigRegistry-3.0-21/AceConfigRegistry-3.0.lua"]:343: in function `app'
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1969: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1957>
[string "=[C]"]: in function `?'
[string "@ElvUI/Core/General/Config.lua"]:1116: in function `?'
[string "@Bistooltip/lib/Ace3/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@FrameXML/ChatFrame.lua"]:4938: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4601: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4637: in function <FrameXML/ChatFrame.lua:4633>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals:
(*temporary) = "AceConfigRegistry-3.0-ElvUI:ValidateOptionsTable(): ElvUI.args.EasyBuff.args.wanted.args.party.args.roleBuffs.args.partyRoleBuffs.args.Tanks.args: expected a table, got 'nil'"

**Comment by phoosa** [comment]
Finally found some time to work on this thing again, I've completely rewritten it from scratch to both add new features and to resolve issues created by WOW API changes and my inability to maintain this code for months.
