### ISSUE TITLE
Priest -  Prayer of Spirit Buff

### ISSUE THREAD

**Issue by Pootch** [phoosa/elvui_easybuff#19]
Prayer of Spirit doesn't work. Instead it uses the single target spirit buff.
Please be so kind and fix it for this great addon.
Wowpatch 3.4.1 (Wotlk Classic)

**Comment by phoosa** [comment]
Finally found some time to work on this thing again, I've completely rewritten it from scratch to both add new features and to resolve issues created by WOW API changes and my inability to maintain this code for months.

Please let me know if this issue has not been resolved with these changes
