### ISSUE TITLE
Priests missing buffs + invalid buff

### ISSUE THREAD

**Issue by mwaterreus** [phoosa/elvui_easybuff#2]
Priests (undead) are missing buffs:
- Touch of Weakness (UD Racial)
- Shadowform
- Greater Shadow Protection is misspelled and should be Prayer of Shadow Protection

Attached snippets have the right values and spell-ids up to level 60 (didnt include lvl70 spells yet). They should be added to the correct sections in the buffs.lua

With this config howver Touch of weakness has an issue where it keeps recasting it if 'Early Monitoring' is enabled.

Hope u can do somehting with this info :-)

```	
TouchWeakness = {
	class 	 = "Priest",
        name     = "Touch of Weakness",
	selfOnly = true,
	multi 	 = nil
},
Shadowform = {
	class 	 = "Priest",
	name     = "Shadowform",
	selfOnly = true,
	multi 	 = nil
},
```

```	
-- Priest: Touch of Weakness
["2652"] = {
	rank  = 1,
	group = "TouchWeakness"
},
["19261"] = {
	rank  = 2,
	group = "TouchWeakness"
},
["19262"] = {
	rank  = 3,
	group = "TouchWeakness"
},
["19264"] = {
	rank  = 4,
	group = "TouchWeakness"
},
["19265"] = {
	rank  = 5,
	group = "TouchWeakness"
},
["19266"] = {
	rank  = 6,
	group = "TouchWeakness"
},
-- Priest: Shadowform
["15473"] = {
	rank  = 1,
	group = "Shadowform"
},
```

**Comment by phoosa** [comment]
Awesome, thanks for the thorough report.  I've just pushed a new release (v1.3.3) that should address everything in this report.
