### ISSUE TITLE
Non-working for french client

### ISSUE THREAD

**Issue by nixxou** [phoosa/elvui_easybuff#4]
I tried to rename spells on the lua file, but that still don't work.
Now i wonder if that's because you use 

unitName, groupRank, partyIndex, unitLevel, unitClass, classFileName, unitZone, isOnline, isDead, unitRole, unitIsML = GetRaidRosterInfo(groupIndex);

You use unitClass, witch is localized instead of classFileName.

**Comment by phoosa** [comment]
This is a duplicate of #1 .  With v1.4.1 you should be good to go
